from enum import Enum, auto


class AutoName(Enum):
    def _generate_next_value_(name, start, count, last_values):
        return name


class Sets(AutoName):
    TOPSUN_BLUE = auto()
    TOPSUN_GREEN = auto()
    TOPSUN_HOLO = auto()
    CARDDASS_RED = auto()
    CARDDASS_GREEN = auto()
    CARDDASS_NEW = auto()
    COROCORO = auto()
    STARTER_RED_GREEN = auto()
    VENDING_3 = auto()
    GAMEBOY = auto()
    CD = auto()
    MASAKI = auto()
    MINI_CD = auto()
    TRAINER_MAG = auto()
    SQUIRTLE_DECK = auto()
    BULBASAUR_DECK = auto()
    CHAMPION_ROAD = auto()
    NATTA_WAKE = auto()
    VS = auto()
    WEB = auto()
    MCDONALDS = auto()
    JR_RALLY = auto()
    TRAINERS = auto()
    LOTTERY = auto()
    BATTLE_ROAD_SUMMER = auto()
    FAN_CLUB = auto()
    PLAYERS_CLUB = auto()
    MEIJI = auto()
    LUCARIO_MYSTERY_OF_MEW = auto()
    LE_STARTER_KIT = auto()
    BATTLE_ROAD_AUGUST = auto()
    GYM_CHALLENGE = auto()
    BONDS_TIME_GYM_CHALLENGE = auto()
    FAIR_CAMPAIGN_711 = auto()
    CHARIZARD_HALF_DECK = auto()
    LEGENDARY_PRESENT_CAMP = auto()
    BATTLE_FESTA = auto()
    PIKACHU_LIBRE = auto()
    UNIQLO = auto()
    SUMMER_THANKSGIVING = auto()
    CHARIZARD_EX_MEGA_BATTLE = auto()
    BUILD_POWER_STYLE = auto()
    POKEMON_CENTER = auto()
    GOLDEN_PRESENT_CAMPAIGN = auto()
    B_SHOCK_R_FLASH = auto()
    POKEMON_GAME_ART_COLLECTION = auto()
    PREMIUM_CHAMPION_PACK = auto()
    POKEMON_CENTER_MEGA_BATTLE = auto()
    LETS_TRADE_PLEASE_20TH = auto()
    ANNIVERSARY_20_SPECIAL = auto()
    ANNIVERSARY_20_BATTLE_FESTA = auto()
    SM_PIKACHU_SPECIAL_BOX = auto()
    PIKACHUS_EASTER = auto()

    BASE = auto()
    ROCKET = auto()
    NEO_2 = auto()
    NEO_3 = auto()
    EXPEDITION = auto()
    THE_TOWN_ON_NO_MAP = auto()
    ROCKET_GANG_STRIKES_BACK = auto()
    GOLDEN_SKY_SILVERY_OCEAN = auto()
    STORMFRONT = auto()
    BW5 = auto()
    BWP = auto()
    WILD_BLAZE = auto()
    REVIVING_LEGENDS = auto()
    XY6 = auto()
    XY7 = auto()
    CP6 = auto()
    POKEKYUN = auto()
